#include <stdio.h>

int main(void) {
	int *p=NULL;
	*p=1;
	return 0;
}

/*
 * GDB core dump analysis:
 * Appending the core dump analysis done in native Ubuntu system
 *
 * - NULL point de-referencing causes segmentation fault (Memory violation)
 *
 *
 * gcc -Wall -Wextra -g3 -o ./bin/null ./null.c
 *
 * parthiban@parthi:~/git/penguintux/learn/C/gdb$ ./bin/null 
 * Segmentation fault (core dumped)
 *
 * parthiban@parthi:~/git/penguintux/learn/C/gdb$ ls -l
 * total 256
 * drwxrwxr-x 2 parthiban parthiban   4096 Oct 12 13:54 bin
 * -rw------- 1 parthiban parthiban 249856 Oct 12 13:36 core
 * -rw-rw-r-- 1 parthiban parthiban    312 Oct 12 13:48 function.c
 * -rw-rw-r-- 1 parthiban parthiban    423 Oct 12 13:55 null.c
 * parthiban@parthi:~/git/penguintux/learn/C/gdb$ file core 
 * core: ELF 64-bit LSB  core file x86-64, version 1 (SYSV), SVR4-style, from './bin/null'
 *
 * GDB session:
 *
 *
 * parthiban@parthi:~/git/penguintux/learn/C/gdb$ gdb --core=./core ./bin/null -q
 * Reading symbols from ./bin/null...done.
 *
 * warning: exec file is newer than core file.
 * [New LWP 13213]
 * Core was generated by `./bin/null'.
 * Program terminated with signal SIGSEGV, Segmentation fault.
 * #0  0x00000000004004fd in main () at ./null.c:5
 * 
 * warning: Source file is more recent than executable.
 * 5		*p=1;
 * (gdb) print p
 * $1 = (int *) 0x0
 * (gdb) q
 *
 */

/*
Enable core dumping in Ubuntu:

>> ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 191535
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 191535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
>>ulimit -c
0
>>ulimit -c unlimited
>>ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 191535
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 191535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited


 */

/*
gdb:
----
./configure --target=arm-linux-gnueabihf
make CROSS_COMPILE=arm-linux-gnueabihf -j16 all

gdbserver:
----------
./configure --host=arm-linux-gnueabihf
make CROSS_COMPILE=arm-linux-gnueabihf -j16 all

Starting gdbserver in target:
-----------------------------
gdbserver <IP address>:12345 ./null

Starting gdb in host:
---------------------
gdb -q ./null
> target remote <IP address>:12345

>> Usual gdb debugging can be continued here

- Non strip binary from development system
- Remote debugging allows to debug target in different location
- Can be used at place where 'core' file generation is not possible

 */
